CREATE DATABASE IF NOT EXISTS restaurant
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_unicode_ci;

USE restaurant;

CREATE TABLE IF NOT EXISTS Gift (
    GiftID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Points_Required_for_Redemption INT NOT NULL,
    Description text,
    PRIMARY KEY (GiftID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Membership_Rule (
    Rule_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Level VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (Rule_ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Customer (
    CustomerID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Password VARCHAR(255) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Phone VARCHAR(20) NOT NULL UNIQUE,
    Point INT UNSIGNED DEFAULT 0,
    CreatedTime TIMESTAMP,
    Rule_ID INT UNSIGNED,
    PRIMARY KEY (CustomerID),
    FOREIGN KEY (Rule_ID) REFERENCES Membership_Rule(Rule_ID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Inventory (
    InventoryID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Inventory_Quantity DECIMAL(10,2) UNSIGNED DEFAULT 0,
    Supplier VARCHAR(50) NOT NULL,
    Unit VARCHAR(20),
    Status VARCHAR(20),
    MinQuantity DECIMAL(10,2),
    PRIMARY KEY (InventoryID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Product (
    ProductID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Image VARCHAR(255),
    PRIMARY KEY (ProductID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS made_from (
    InventoryID INT UNSIGNED,
    ProductID INT UNSIGNED,
    Quantity DECIMAL(8,2) NOT NULL,
    PRIMARY KEY (InventoryID, ProductID),
    FOREIGN KEY (InventoryID) REFERENCES Inventory(InventoryID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Order` (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    OrderID INT UNSIGNED NOT NULL,
    Order_Status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    Special_Requests VARCHAR(200),
    Total_Amount DECIMAL(10,2) NOT NULL,
    Order_Time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS placed_by (
    OrderID INT UNSIGNED,
    CustomerID INT UNSIGNED,
    PRIMARY KEY (OrderID),
    FOREIGN KEY (OrderID) REFERENCES `Order`(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS contain (
    ID INT UNSIGNED,
    ProductID INT UNSIGNED,
    Quantity INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID, ProductID),
    FOREIGN KEY (ID) REFERENCES `Order`(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Staff (
    StaffID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Password VARCHAR(255) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Phone VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY (StaffID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS process (
    StaffID INT UNSIGNED,
    OrderID INT UNSIGNED,
    PRIMARY KEY (StaffID, OrderID),
    FOREIGN KEY (StaffID) REFERENCES Staff(StaffID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (OrderID) REFERENCES `Order`(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Table` (
    TableID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Capacity INT UNSIGNED NOT NULL,
    Occupancy_Status VARCHAR(20),
    Table_Number VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY (TableID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Reservation (
    ReservationID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Number_of_Reserved_Guests INT UNSIGNED NOT NULL,
    Reservation_Time TIME NOT NULL,
    Reservation_Date DATE NOT NULL,
    CustomerID INT UNSIGNED,
    notes TEXT,
    PRIMARY KEY (ReservationID),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS reserve (
    ReservationID INT UNSIGNED,
    TableID INT UNSIGNED,
    PRIMARY KEY (ReservationID, TableID),
    FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (TableID) REFERENCES `Table`(TableID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Exchange (
    ExchangeID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    GiftID INT UNSIGNED,
    CustomerID INT UNSIGNED,
    PRIMARY KEY (ExchangeID),
    FOREIGN KEY (GiftID) REFERENCES Gift(GiftID)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE = InnoDB;
ALTER TABLE Staff ADD Avatar LONGBLOB;